version: "3"

services:
  database:
    image: "postgres:latest"
    container_name: database_postgre
    ports:
      - "5432:5432"  # maps container port 5432 to host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db-data:/var/lib/postgresql # persist data outside the container
    networks:
      - shop-pricer

networks:
  shop-pricer:
    external: true
